param(
  [string]$SourceRoot='D:\mywiki\FightingAgainstDisorder',
  [string]$ProjectRoot=(Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference='Stop'
$utf8=New-Object System.Text.UTF8Encoding($false)
$OutRoot=Join-Path $ProjectRoot 'fighting-against-disorder'
$AssetRoot=Join-Path $OutRoot 'assets'
New-Item -ItemType Directory -Force -Path $OutRoot,$AssetRoot | Out-Null

$pages=@(
  [ordered]@{Id='entropy-basics';Source='01-原理篇\01-什么是熵与熵增定律.md';File='entropy-basics.html';Group='principles';GroupName='01 · 原理篇';Label='什么是熵与熵增定律';Visual='entropy';Minutes=7;Micro='环顾你现在所在的位置，找出一个“不干预就会继续变乱”的对象。先只观察，不急着整理。'},
  [ordered]@{Id='why-order-breaks';Source='01-原理篇\02-有序为何总会崩坏.md';File='why-order-breaks.html';Group='principles';GroupName='01 · 原理篇';Label='有序为何总会崩坏';Visual='cards';Minutes=7;Micro='拿一副牌或十张便签做一次随机排列，感受“整齐状态少、混乱状态多”的概率差异。'},
  [ordered]@{Id='information-entropy';Source='01-原理篇\03-信息熵与生活中的熵.md';File='information-entropy.html';Group='principles';GroupName='01 · 原理篇';Label='信息熵与生活中的熵';Visual='search';Minutes=8;Micro='记录今天一次“找东西或找信息”花掉的时间，这就是你正在支付的信息熵成本。'},
  [ordered]@{Id='open-systems';Source='01-原理篇\04-开放系统与负熵.md';File='open-systems.html';Group='principles';GroupName='01 · 原理篇';Label='开放系统与负熵';Visual='open';Minutes=8;Micro='找出一个你正在维持的秩序系统，写下它依赖的三种外部输入：时间、能量或信息。'},
  [ordered]@{Id='order-costs-energy';Source='01-原理篇\05-维持秩序必然耗能.md';File='order-costs-energy.html';Group='principles';GroupName='01 · 原理篇';Label='维持秩序必然耗能';Visual='energy';Minutes=8;Micro='选一个反复崩坏的领域，判断你的能量主要花在源头、系统、维护，还是崩溃后的重建。'},
  [ordered]@{Id='entropy-signals';Source='02-认知篇\01-熵增在生活工作中的表现.md';File='entropy-signals.html';Group='mindset';GroupName='02 · 认知篇';Label='熵增在生活工作中的表现';Visual='radar';Minutes=9;Micro='给六个领域各打 1—5 分，只圈出得分最高的一项，作为第一个杠杆点。'},
  [ordered]@{Id='minimum-energy';Source='02-认知篇\02-最小能耗原则.md';File='minimum-energy.html';Group='mindset';GroupName='02 · 认知篇';Label='最小能耗原则';Visual='levers';Minutes=8;Micro='把你最近想坚持的一件事缩小到“三个月后也愿意做”的版本。'},
  [ordered]@{Id='common-mistakes';Source='02-认知篇\03-常见误区.md';File='common-mistakes.html';Group='mindset';GroupName='02 · 认知篇';Label='常见误区';Visual='fork';Minutes=7;Micro='从六个误区中圈出你最常犯的一个，并写下与它相反的低能耗做法。'},
  [ordered]@{Id='messy-room';Source='03-案例篇\01-越来越乱的桌面与房间.md';File='messy-room.html';Group='cases';GroupName='03 · 案例篇';Label='越来越乱的桌面与房间';Visual='room';Minutes=8;Micro='列出每天最常找的 5 样物品，今天只给其中 1 样指定一个离使用点最近的家。'},
  [ordered]@{Id='digital-clutter';Source='03-案例篇\02-失控的文件与数字资料.md';File='digital-clutter.html';Group='cases';GroupName='03 · 案例篇';Label='失控的文件与数字资料';Visual='files';Minutes=8;Micro='建立一个 Inbox 临时入口，并把桌面上 5 个散落文件先移进去。'},
  [ordered]@{Id='overloaded-calendar';Source='03-案例篇\03-被塞满的日程与时间.md';File='overloaded-calendar.html';Group='cases';GroupName='03 · 案例篇';Label='被塞满的日程与时间';Visual='calendar';Minutes=8;Micro='从本周日历中删除或缩短一个低价值安排，为缓冲区让出 30 分钟。'},
  [ordered]@{Id='team-entropy';Source='03-案例篇\04-团队协作与项目的熵增.md';File='team-entropy.html';Group='cases';GroupName='03 · 案例篇';Label='团队协作与项目的熵增';Visual='team';Minutes=9;Micro='为一个正在进行的任务确认唯一 Owner 和唯一信息源。'},
  [ordered]@{Id='habit-decay';Source='03-案例篇\05-退化的健康与习惯.md';File='habit-decay.html';Group='cases';GroupName='03 · 案例篇';Label='退化的健康与习惯';Visual='habit';Minutes=8;Micro='把一个健康习惯缩小为“两分钟版本”，并绑定到一个已经稳定存在的动作之后。'},
  [ordered]@{Id='reduce-input';Source='04-方法篇\01-从源头减少熵产生.md';File='reduce-input.html';Group='methods';GroupName='04 · 方法篇';Label='从源头减少熵产生';Visual='funnel';Minutes=8;Micro='今天关闭一个通知、退订一个信息源，或拒绝一个没有明确价值的新输入。'},
  [ordered]@{Id='systems-not-willpower';Source='04-方法篇\02-建立系统而非依赖意志.md';File='systems-not-willpower.html';Group='methods';GroupName='04 · 方法篇';Label='建立系统而非依赖意志';Visual='system';Minutes=9;Micro='把一句“我要记得……”改写成一个默认值、自动化、摩擦设计或检查清单。'},
  [ordered]@{Id='small-frequent-maintenance';Source='04-方法篇\03-定期小步清理机制.md';File='small-frequent-maintenance.html';Group='methods';GroupName='04 · 方法篇';Label='定期小步清理机制';Visual='curve';Minutes=8;Micro='现在做一次不超过 2 分钟的微维护，并为它设定固定触发点。'},
  [ordered]@{Id='external-order';Source='04-方法篇\04-结构化与外部秩序.md';File='external-order.html';Group='methods';GroupName='04 · 方法篇';Label='结构化与外部秩序';Visual='zones';Minutes=9;Micro='选一个抽屉或文件夹，只完成分区、命名、可视化中的一项改造。'},
  [ordered]@{Id='personal-system';Source='05-落地篇\01-个人生活落地方案.md';File='personal-system.html';Group='action';GroupName='05 · 落地篇';Label='个人生活落地方案';Visual='personal';Minutes=10;Micro='从家居、数字、财务中只选一个领域，建立一条最小规则。'},
  [ordered]@{Id='work-system';Source='05-落地篇\02-工作场景落地方案.md';File='work-system.html';Group='action';GroupName='05 · 落地篇';Label='工作场景落地方案';Visual='workflow';Minutes=10;Micro='为工作信息确定三个唯一入口：消息、任务、文档各放在哪里。'},
  [ordered]@{Id='thirty-day-plan';Source='05-落地篇\03-30天行动计划.md';File='thirty-day-plan.html';Group='action';GroupName='05 · 落地篇';Label='30 天行动计划';Visual='steps';Minutes=12;Micro='完成第 1 天：做一次熵增体检，并写下本月唯一要改造的领域。'},
  [ordered]@{Id='review-iterate';Source='05-落地篇\04-复盘与迭代.md';File='review-iterate.html';Group='action';GroupName='05 · 落地篇';Label='复盘与迭代';Visual='review';Minutes=8;Micro='预约本周第一次 15 分钟回顾，只回答：哪里又乱了？系统哪里没兜住？'},
  [ordered]@{Id='templates';Source='06-工具与模板\01-清单与模板合集.md';File='templates.html';Group='tools';GroupName='06 · 工具与模板';Label='清单与模板合集';Visual='toolbox';Minutes=10;Micro='不要一次复制全部模板：先选一个当前问题最相关的模板开始。'},
  [ordered]@{Id='tools';Source='06-工具与模板\02-工具推荐.md';File='tools.html';Group='tools';GroupName='06 · 工具与模板';Label='工具推荐';Visual='decision';Minutes=8;Micro='先写下你真正要降低的摩擦，再判断是否需要增加一个新工具。'}
)

$bySource=@{};$byId=@{};for($i=0;$i -lt $pages.Count;$i++){ $pages[$i].Index=$i+1;$bySource[$pages[$i].Source.Replace('\','/')]=$pages[$i];$byId[$pages[$i].Id]=$pages[$i] }
$groups=[ordered]@{
  principles=@{Name='01 · 原理篇';Goal='理解无序为什么是默认趋势';Ids=@('entropy-basics','why-order-breaks','information-entropy','open-systems','order-costs-energy')}
  mindset=@{Name='02 · 认知篇';Goal='建立识别熵增的思维模型';Ids=@('entropy-signals','minimum-energy','common-mistakes')}
  cases=@{Name='03 · 案例篇';Goal='看清无序如何在真实场景里发生';Ids=@('messy-room','digital-clutter','overloaded-calendar','team-entropy','habit-decay')}
  methods=@{Name='04 · 方法篇';Goal='掌握四种可迁移的低能耗方法';Ids=@('reduce-input','systems-not-willpower','small-frequent-maintenance','external-order')}
  action=@{Name='05 · 落地篇';Goal='把方法变成个人与工作的运行系统';Ids=@('personal-system','work-system','thirty-day-plan','review-iterate')}
  tools=@{Name='06 · 工具与模板';Goal='复制清单并选择低摩擦工具';Ids=@('templates','tools')}
}

function E([string]$s){return [System.Net.WebUtility]::HtmlEncode($s)}
function Inline([string]$s,[string]$source){
  if(!$s){return ''}
  $s=[regex]::Replace($s,'!\[([^\]]*)\]\(([^)]+)\)',{param($m)'<span class="fad-image-note">'+(E $m.Groups[1].Value)+'</span>'})
  $s=[regex]::Replace($s,'\[([^\]]+)\]\(([^)]+)\)',{
    param($m)
    $label=$m.Groups[1].Value;$target=$m.Groups[2].Value
    if($target.StartsWith('http')){return '<a href="'+(E $target)+'" target="_blank" rel="noopener">'+(E $label)+'</a>'}
    $parts=$target -split '#',2;$path=$parts[0];$anchor=if($parts.Count -gt 1){'#'+$parts[1]}else{''}
    if(!$path){return '<a href="'+(E $anchor)+'">'+(E $label)+'</a>'}
    if($path -eq '../README.md' -or $path -eq 'README.md'){return '<a href="index.html">'+(E $label)+'</a>'}
    $base=[IO.Path]::GetDirectoryName($source).Replace('\','/');$combined=if($base){$base+'/'+$path}else{$path}
    $segments=New-Object Collections.Generic.List[string]
    foreach($seg in $combined.Split('/')){if($seg -eq '..'){if($segments.Count){$segments.RemoveAt($segments.Count-1)}}elseif($seg -and $seg -ne '.'){$segments.Add($seg)}}
    $norm=($segments -join '/')
    if($bySource.ContainsKey($norm)){return '<a href="'+$bySource[$norm].File+'">'+(E $label)+'</a>'}
    return '<span>'+ (E $label) +'</span>'
  })
  $s=[regex]::Replace($s,'`([^`]+)`','<code>$1</code>')
  $s=[regex]::Replace($s,'\*\*([^*]+)\*\*','<strong>$1</strong>')
  $s=[regex]::Replace($s,'(?<!\*)\*([^*]+)\*(?!\*)','<em>$1</em>')
  return $s
}
function Slug([string]$s,[int]$n){$v=[regex]::Replace($s,'[^\p{L}\p{Nd}]+','-').Trim('-').ToLower();if(!$v){$v='section-'+$n};return $v}
function Markdown([string]$md,[string]$source,[ref]$toc,[bool]$templates){
  $lines=$md -split "`r?`n";$out=New-Object Text.StringBuilder;$para=New-Object Collections.Generic.List[string];$state=@{List=''};$quote=New-Object Collections.Generic.List[string];$code=New-Object Collections.Generic.List[string];$inCode=$false;$table=New-Object Collections.Generic.List[string];$headCount=0;$codeCount=0
  function FlushPara(){if($para.Count){[void]$out.Append('<p>'+ (Inline (($para -join ' ') ) $source) +'</p>');$para.Clear()}}
  function FlushList(){if($state.List){[void]$out.Append('</'+$state.List+'>');$state.List=''}}
  function FlushQuote(){if($quote.Count){[void]$out.Append('<blockquote><p>'+ (Inline (($quote -join '<br>')) $source) +'</p></blockquote>');$quote.Clear()}}
  function FlushTable(){if($table.Count -ge 2){$rows=@();foreach($line in $table){$rows+=,@(($line.Trim('|') -split '\|')|ForEach-Object{$_.Trim()})};[void]$out.Append('<table><thead><tr>');foreach($c in $rows[0]){[void]$out.Append('<th>'+(Inline $c $source)+'</th>')};[void]$out.Append('</tr></thead><tbody>');for($ri=2;$ri -lt $rows.Count;$ri++){[void]$out.Append('<tr>');foreach($c in $rows[$ri]){[void]$out.Append('<td>'+(Inline $c $source)+'</td>')};[void]$out.Append('</tr>')};[void]$out.Append('</tbody></table>')};$table.Clear()}
  foreach($line in $lines){
    if($line -match '^```'){FlushPara;FlushList;FlushQuote;FlushTable;if($inCode){$codeCount++;$cid='tpl-'+$codeCount;$button=if($templates){'<button class="fad-copy" data-copy-target="'+$cid+'">复制模板</button>'}else{''};[void]$out.Append('<pre>'+$button+'<code id="'+$cid+'">'+(E ($code -join "`n"))+'</code></pre>');$code.Clear();$inCode=$false}else{$inCode=$true};continue}
    if($inCode){$code.Add($line);continue}
    if($line -match '^\s*\|.*\|\s*$'){FlushPara;FlushList;FlushQuote;$table.Add($line);continue}else{FlushTable}
    if([string]::IsNullOrWhiteSpace($line)){FlushPara;FlushList;FlushQuote;continue}
    if($line -match '^# '){continue}
    if($line -match '^(##|###)\s+(.+)$'){FlushPara;FlushList;FlushQuote;$level=$Matches[1].Length;$title=$Matches[2];$headCount++;$id=Slug $title $headCount;$toc.Value+=,@{Level=$level;Id=$id;Title=$title};[void]$out.Append('<h'+$level+' id="'+$id+'">'+(Inline $title $source)+'</h'+$level+'>');continue}
    if($line -match '^>\s?(.*)$'){$quote.Add($Matches[1]);continue}
    if($line -match '^---+$'){FlushPara;FlushList;FlushQuote;[void]$out.Append('<hr>');continue}
    if($line -match '^\s*[-*]\s+\[([ xX])\]\s+(.+)$'){FlushPara;if($state.List -ne 'ul'){FlushList;$state.List='ul';[void]$out.Append('<ul class="fad-checklist">')};$checked=if($Matches[1] -match '[xX]'){' checked'}else{''};[void]$out.Append('<li><label><input class="fad-check" type="checkbox"'+$checked+'>'+(Inline $Matches[2] $source)+'</label></li>');continue}
    if($line -match '^\s*[-*]\s+(.+)$'){FlushPara;if($state.List -ne 'ul'){FlushList;$state.List='ul';[void]$out.Append('<ul>')};[void]$out.Append('<li>'+(Inline $Matches[1] $source)+'</li>');continue}
    if($line -match '^\s*\d+[\.、]\s+(.+)$'){FlushPara;if($state.List -ne 'ol'){FlushList;$state.List='ol';[void]$out.Append('<ol>')};[void]$out.Append('<li>'+(Inline $Matches[1] $source)+'</li>');continue}
    $para.Add($line.Trim())
  }
  FlushPara;FlushList;FlushQuote;FlushTable
  return $out.ToString()
}

function Diagram([string]$type,[string]$title){
  $head='<figure class="fad-figure"><svg viewBox="0 0 760 360" role="img" aria-label="'+(E $title)+'"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 8 4 0 8Z" fill="var(--fad-amber)"/></marker><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="var(--fad-navy-2)"/><stop offset="1" stop-color="var(--fad-amber)"/></linearGradient></defs>'
  $tail='</svg><figcaption>用一张图建立直觉：先看关系，再回到文字理解细节。</figcaption></figure>'
  $map=@{}
  $map.entropy='<text x="380" y="30" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">同一张桌子：有序状态很少，混乱状态极多</text><rect x="55" y="70" width="250" height="220" rx="18" fill="var(--fad-surface-2)" stroke="var(--fad-good)" stroke-width="2"/><rect x="90" y="115" width="180" height="120" rx="8" fill="none" stroke="var(--fad-good)"/><circle cx="130" cy="150" r="12" fill="var(--fad-amber)"/><rect x="170" y="140" width="55" height="18" rx="3" fill="var(--fad-navy-2)"/><text x="180" y="270" text-anchor="middle" fill="var(--fad-good)" font-weight="700">少数有序状态</text><path d="M330 180H425" stroke="var(--fad-amber)" stroke-width="4" marker-end="url(#a)"/><rect x="455" y="70" width="250" height="220" rx="18" fill="var(--fad-surface-2)" stroke="var(--fad-danger)" stroke-width="2"/><g fill="var(--fad-amber)"><circle cx="500" cy="110" r="9"/><circle cx="650" cy="128" r="7"/><circle cx="535" cy="240" r="12"/><circle cx="620" cy="205" r="8"/></g><g fill="var(--fad-navy-2)"><rect x="565" y="90" width="48" height="16" rx="3"/><rect x="485" y="185" width="55" height="18" rx="3" transform="rotate(22 485 185)"/><rect x="625" y="250" width="42" height="15" rx="3" transform="rotate(-16 625 250)"/></g><text x="580" y="270" text-anchor="middle" fill="var(--fad-danger)" font-weight="700">海量混乱状态</text><text x="380" y="330" text-anchor="middle" fill="var(--fad-muted)">随机使用时，系统更容易落入“可能性更多”的一侧</text>'
  $map.cards='<text x="380" y="34" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">概率碾压：一种顺序，对阵海量乱序</text><g transform="translate(70 90)"><rect width="70" height="105" rx="8" fill="var(--fad-surface)" stroke="var(--fad-good)" stroke-width="2"/><rect x="18" y="18" width="34" height="50" rx="4" fill="none" stroke="var(--fad-good)"/><text x="35" y="92" text-anchor="middle" fill="var(--fad-good)">唯一目标</text></g><path d="M175 142H285" stroke="var(--fad-amber)" stroke-width="4" marker-end="url(#a)"/><g transform="translate(315 65)" fill="var(--fad-surface)" stroke="var(--fad-danger)"><rect x="0" y="0" width="68" height="96" rx="7" transform="rotate(-12 34 48)"/><rect x="65" y="20" width="68" height="96" rx="7" transform="rotate(8 99 68)"/><rect x="135" y="-5" width="68" height="96" rx="7" transform="rotate(18 169 43)"/><rect x="210" y="35" width="68" height="96" rx="7" transform="rotate(-5 244 83)"/><rect x="282" y="2" width="68" height="96" rx="7" transform="rotate(13 316 50)"/></g><text x="500" y="235" text-anchor="middle" fill="var(--fad-danger)" font-weight="700">几乎所有随机排列都算“乱”</text><text x="380" y="300" text-anchor="middle" fill="var(--fad-muted)">秩序会自发衰减，却不会靠随机动作自发恢复</text>'
  $map.search='<text x="380" y="32" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">信息越无结构，搜索路径越长</text><g stroke="var(--fad-border)" fill="var(--fad-surface)"><rect x="55" y="75" width="165" height="70" rx="12"/><rect x="55" y="165" width="165" height="70" rx="12"/><rect x="55" y="255" width="165" height="55" rx="12"/></g><text x="137" y="116" text-anchor="middle" fill="var(--fad-muted)">文件 01 / 最终 / 新</text><text x="137" y="206" text-anchor="middle" fill="var(--fad-muted)">截图 / 未分类 / 其他</text><text x="137" y="288" text-anchor="middle" fill="var(--fad-muted)">消息 999+</text><path d="M240 192C340 90 410 300 505 174" fill="none" stroke="var(--fad-danger)" stroke-width="4" stroke-dasharray="8 6" marker-end="url(#a)"/><circle cx="565" cy="174" r="70" fill="none" stroke="var(--fad-amber)" stroke-width="6"/><path d="M615 224l60 60" stroke="var(--fad-amber)" stroke-width="12" stroke-linecap="round"/><text x="380" y="330" text-anchor="middle" fill="var(--fad-muted)">混乱真正收取的费用，往往不是空间，而是每一次寻找</text>'
  $map.open='<text x="380" y="30" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">开放系统：输入能量，维持局部秩序，向外排出熵</text><path d="M50 180H245" stroke="var(--fad-amber)" stroke-width="5" marker-end="url(#a)"/><text x="130" y="158" text-anchor="middle" fill="var(--fad-amber)" font-weight="700">能量 / 信息输入</text><circle cx="380" cy="180" r="112" fill="var(--fad-surface-2)" stroke="var(--fad-good)" stroke-width="3"/><g fill="var(--fad-good)"><circle cx="340" cy="145" r="12"/><circle cx="420" cy="145" r="12"/><circle cx="340" cy="215" r="12"/><circle cx="420" cy="215" r="12"/></g><path d="M340 145H420V215H340Z" fill="none" stroke="var(--fad-good)" stroke-width="2"/><text x="380" y="188" text-anchor="middle" fill="var(--fad-ink)" font-weight="700">局部秩序</text><path d="M495 180H705" stroke="var(--fad-danger)" stroke-width="5" marker-end="url(#a)"/><text x="610" y="158" text-anchor="middle" fill="var(--fad-danger)" font-weight="700">废物 / 热量 / 噪声</text>'
  $map.energy='<text x="380" y="30" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">同样一份能量，花在不同位置，收益完全不同</text><g font-size="13"><text x="100" y="90" fill="var(--fad-muted)">崩溃后重建</text><rect x="210" y="70" width="450" height="28" rx="14" fill="var(--fad-danger)" opacity=".75"/><text x="100" y="160" fill="var(--fad-muted)">日常小维护</text><rect x="210" y="140" width="230" height="28" rx="14" fill="var(--fad-amber)"/><text x="100" y="230" fill="var(--fad-muted)">系统与默认</text><rect x="210" y="210" width="145" height="28" rx="14" fill="var(--fad-good)"/><text x="100" y="300" fill="var(--fad-muted)">源头减量</text><rect x="210" y="280" width="85" height="28" rx="14" fill="var(--fad-good)"/></g><text x="675" y="91" fill="var(--fad-danger)">最贵</text><text x="310" y="330" fill="var(--fad-muted)">一次性设计投入 → 长期节省维护能量</text>'
  $map.radar='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">六大领域熵增体检</text><g transform="translate(380 185)" fill="none" stroke="var(--fad-border)"><polygon points="0,-125 108,-62 108,62 0,125 -108,62 -108,-62"/><polygon points="0,-82 71,-41 71,41 0,82 -71,41 -71,-41"/><line x1="0" y1="0" x2="0" y2="-125"/><line x1="0" y1="0" x2="108" y2="-62"/><line x1="0" y1="0" x2="108" y2="62"/><line x1="0" y1="0" x2="0" y2="125"/><line x1="0" y1="0" x2="-108" y2="62"/><line x1="0" y1="0" x2="-108" y2="-62"/><polygon points="0,-92 76,-44 60,35 0,105 -88,51 -52,-30" fill="rgba(217,155,66,.25)" stroke="var(--fad-amber)" stroke-width="3"/></g><g fill="var(--fad-muted)" font-size="12"><text x="380" y="46" text-anchor="middle">物理空间</text><text x="525" y="112">数字信息</text><text x="526" y="270">时间日程</text><text x="380" y="338" text-anchor="middle">团队项目</text><text x="145" y="270">身体习惯</text><text x="142" y="112">人际情绪</text></g>'
  $map.levers='<text x="380" y="30" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">最小能耗的三大杠杆</text><g><circle cx="185" cy="180" r="92" fill="rgba(217,155,66,.13)" stroke="var(--fad-amber)" stroke-width="3"/><circle cx="380" cy="180" r="92" fill="rgba(54,129,107,.12)" stroke="var(--fad-good)" stroke-width="3"/><circle cx="575" cy="180" r="92" fill="var(--fad-surface-2)" stroke="var(--fad-navy-2)" stroke-width="3"/></g><g text-anchor="middle"><text x="185" y="172" fill="var(--fad-ink)" font-size="18" font-weight="700">源头减量</text><text x="185" y="199" fill="var(--fad-muted)" font-size="12">让要维护的更少</text><text x="380" y="172" fill="var(--fad-ink)" font-size="18" font-weight="700">系统与默认</text><text x="380" y="199" fill="var(--fad-muted)" font-size="12">让做对不用动脑</text><text x="575" y="172" fill="var(--fad-ink)" font-size="18" font-weight="700">小步高频</text><text x="575" y="199" fill="var(--fad-muted)" font-size="12">别等崩溃再重建</text><text x="380" y="325" fill="var(--fad-amber)" font-size="15" font-weight="700">可持续性 ＞ 一时强度</text></g>'
  $map.fork='<text x="380" y="30" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">面对混乱时，两条完全不同的路径</text><path d="M100 180H290" stroke="var(--fad-amber)" stroke-width="5" marker-end="url(#a)"/><circle cx="85" cy="180" r="36" fill="var(--fad-surface-2)" stroke="var(--fad-amber)"/><text x="85" y="185" text-anchor="middle" fill="var(--fad-ink)" font-weight="700">回潮</text><path d="M300 180C380 180 370 90 455 90H680" fill="none" stroke="var(--fad-danger)" stroke-width="4" marker-end="url(#a)"/><path d="M300 180C380 180 370 270 455 270H680" fill="none" stroke="var(--fad-good)" stroke-width="4" marker-end="url(#a)"/><text x="520" y="70" fill="var(--fad-danger)" font-weight="700">怪自己 → 爆发整理 → 再次崩坏</text><text x="520" y="250" fill="var(--fad-good)" font-weight="700">读信号 → 改系统 → 低耗维持</text>'
  $map.room='<text x="380" y="30" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">房间熵增的关键路径</text><rect x="60" y="85" width="180" height="210" rx="18" fill="var(--fad-surface-2)" stroke="var(--fad-border)"/><text x="150" y="115" text-anchor="middle" fill="var(--fad-muted)">不断进入</text><g fill="var(--fad-amber)"><circle cx="110" cy="155" r="10"/><rect x="145" y="145" width="55" height="20" rx="4"/><circle cx="180" cy="205" r="12"/><rect x="92" y="225" width="50" height="18" rx="4"/></g><path d="M260 190H365" stroke="var(--fad-danger)" stroke-width="4" marker-end="url(#a)"/><rect x="385" y="105" width="130" height="170" rx="12" fill="rgba(181,92,76,.12)" stroke="var(--fad-danger)" stroke-dasharray="7 5"/><text x="450" y="190" text-anchor="middle" fill="var(--fad-danger)" font-weight="700">暂放区</text><path d="M535 190H650" stroke="var(--fad-good)" stroke-width="4" marker-end="url(#a)"/><rect x="660" y="120" width="60" height="60" rx="8" fill="rgba(54,129,107,.15)" stroke="var(--fad-good)"/><rect x="660" y="205" width="60" height="60" rx="8" fill="rgba(54,129,107,.15)" stroke="var(--fad-good)"/><text x="690" y="105" text-anchor="middle" fill="var(--fad-good)">固定的家</text><text x="380" y="330" text-anchor="middle" fill="var(--fad-muted)">拦入口、消灭暂放区、缩短归位路径</text>'
  $map.files='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">从平铺失控到三层结构</text><g fill="var(--fad-surface)" stroke="var(--fad-danger)"><rect x="45" y="75" width="110" height="40" rx="7"/><rect x="90" y="135" width="110" height="40" rx="7"/><rect x="45" y="200" width="110" height="40" rx="7"/><rect x="115" y="260" width="110" height="40" rx="7"/></g><path d="M250 185H355" stroke="var(--fad-amber)" stroke-width="4" marker-end="url(#a)"/><g fill="var(--fad-surface)" stroke="var(--fad-good)"><rect x="390" y="65" width="150" height="45" rx="8"/><rect x="440" y="140" width="150" height="45" rx="8"/><rect x="490" y="215" width="150" height="45" rx="8"/></g><path d="M465 110V140M515 185V215" stroke="var(--fad-good)" stroke-width="3"/><text x="465" y="93" text-anchor="middle" fill="var(--fad-ink)">入口 Inbox</text><text x="515" y="168" text-anchor="middle" fill="var(--fad-ink)">≤ 7 个顶层类目</text><text x="565" y="243" text-anchor="middle" fill="var(--fad-ink)">统一命名 / 归档</text><text x="380" y="325" text-anchor="middle" fill="var(--fad-muted)">结构的目标不是漂亮，而是缩短寻找路径</text>'
  $map.calendar='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">时间系统也需要缓冲区</text><rect x="55" y="70" width="280" height="230" rx="16" fill="var(--fad-surface)" stroke="var(--fad-danger)"/><g fill="var(--fad-danger)" opacity=".65"><rect x="80" y="100" width="230" height="30" rx="5"/><rect x="80" y="140" width="230" height="30" rx="5"/><rect x="80" y="180" width="230" height="30" rx="5"/><rect x="80" y="220" width="230" height="30" rx="5"/><rect x="80" y="260" width="230" height="20" rx="5"/></g><text x="195" y="325" text-anchor="middle" fill="var(--fad-danger)">满载：一点波动就开始救火</text><rect x="425" y="70" width="280" height="230" rx="16" fill="var(--fad-surface)" stroke="var(--fad-good)"/><g fill="var(--fad-good)" opacity=".72"><rect x="450" y="100" width="230" height="34" rx="5"/><rect x="450" y="160" width="180" height="34" rx="5"/><rect x="450" y="245" width="210" height="34" rx="5"/></g><rect x="450" y="205" width="230" height="22" rx="5" fill="rgba(217,155,66,.2)" stroke="var(--fad-amber)" stroke-dasharray="5 4"/><text x="565" y="220" text-anchor="middle" fill="var(--fad-amber)" font-size="11">缓冲区</text><text x="565" y="325" text-anchor="middle" fill="var(--fad-good)">留白：吸收波动，保护重要事项</text>'
  $map.team='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">人数增加，潜在沟通链路快速膨胀</text><g fill="var(--fad-amber)"><circle cx="155" cy="165" r="22"/><circle cx="260" cy="105" r="22"/><circle cx="260" cy="225" r="22"/></g><g stroke="var(--fad-danger)" stroke-width="2"><line x1="175" y1="153" x2="240" y2="117"/><line x1="175" y1="177" x2="240" y2="213"/><line x1="260" y1="127" x2="260" y2="203"/></g><path d="M315 165H420" stroke="var(--fad-amber)" stroke-width="4" marker-end="url(#a)"/><rect x="455" y="70" width="210" height="200" rx="18" fill="var(--fad-surface-2)" stroke="var(--fad-good)"/><text x="560" y="105" text-anchor="middle" fill="var(--fad-good)" font-weight="700">用结构降低连接复杂度</text><text x="560" y="150" text-anchor="middle" fill="var(--fad-ink)">唯一 Owner</text><text x="560" y="185" text-anchor="middle" fill="var(--fad-ink)">单一信息源</text><text x="560" y="220" text-anchor="middle" fill="var(--fad-ink)">固定协作节奏</text><text x="380" y="325" text-anchor="middle" fill="var(--fad-muted)">团队秩序不是靠每个人更努力，而是靠更少、更清晰的连接</text>'
  $map.habit='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">好习惯不会静止：要么被维护，要么慢慢衰减</text><line x1="75" y1="290" x2="700" y2="290" stroke="var(--fad-border)"/><line x1="75" y1="290" x2="75" y2="60" stroke="var(--fad-border)"/><path d="M80 90C220 105 300 190 455 270" fill="none" stroke="var(--fad-danger)" stroke-width="4"/><path d="M80 90C180 110 200 145 260 150S350 115 420 145S520 115 610 145S670 130 700 135" fill="none" stroke="var(--fad-good)" stroke-width="4"/><g fill="var(--fad-amber)"><circle cx="260" cy="150" r="7"/><circle cx="420" cy="145" r="7"/><circle cx="610" cy="145" r="7"/></g><text x="500" y="255" fill="var(--fad-danger)">没有供能：自然滑落</text><text x="470" y="110" fill="var(--fad-good)">触发式微维护：稳定在可接受区间</text><text x="380" y="330" text-anchor="middle" fill="var(--fad-muted)">追求不连断两次，而不是永不波动</text>'
  $map.funnel='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">最高杠杆发生在入口</text><path d="M80 70H680L545 260H215Z" fill="rgba(217,155,66,.12)" stroke="var(--fad-amber)" stroke-width="3"/><g fill="var(--fad-navy-2)"><circle cx="170" cy="105" r="9"/><circle cx="260" cy="110" r="9"/><circle cx="350" cy="100" r="9"/><circle cx="445" cy="112" r="9"/><circle cx="560" cy="98" r="9"/></g><line x1="300" y1="72" x2="300" y2="165" stroke="var(--fad-danger)" stroke-width="5"/><text x="300" y="60" text-anchor="middle" fill="var(--fad-danger)">拒绝 / 退订 / 一进一出</text><circle cx="380" cy="292" r="24" fill="var(--fad-good)"/><text x="380" y="298" text-anchor="middle" fill="#fff" font-weight="700">少</text><text x="380" y="340" text-anchor="middle" fill="var(--fad-muted)">少一份输入，就永久少一份分类、寻找和维护成本</text>'
  $map.system='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">把“记得做”改造成“不用记得也做对”</text><circle cx="380" cy="185" r="70" fill="rgba(217,155,66,.14)" stroke="var(--fad-amber)" stroke-width="3"/><text x="380" y="180" text-anchor="middle" fill="var(--fad-ink)" font-weight="700">低能耗</text><text x="380" y="204" text-anchor="middle" fill="var(--fad-ink)" font-weight="700">秩序系统</text><g fill="var(--fad-surface)" stroke="var(--fad-good)"><rect x="110" y="75" width="150" height="65" rx="14"/><rect x="500" y="75" width="150" height="65" rx="14"/><rect x="110" y="240" width="150" height="65" rx="14"/><rect x="500" y="240" width="150" height="65" rx="14"/></g><g text-anchor="middle" fill="var(--fad-ink)"><text x="185" y="114">默认值</text><text x="575" y="114">自动化</text><text x="185" y="279">约束与摩擦</text><text x="575" y="279">清单与流程</text></g><g stroke="var(--fad-amber)" stroke-width="3"><line x1="260" y1="112" x2="325" y2="155"/><line x1="500" y1="112" x2="435" y2="155"/><line x1="260" y1="270" x2="325" y2="220"/><line x1="500" y1="270" x2="435" y2="220"/></g>'
  $map.curve='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">维护成本随混乱程度加速上升</text><line x1="75" y1="290" x2="700" y2="290" stroke="var(--fad-border)"/><line x1="75" y1="290" x2="75" y2="55" stroke="var(--fad-border)"/><path d="M80 282C250 278 420 245 510 175S625 75 700 62" fill="none" stroke="var(--fad-danger)" stroke-width="5"/><path d="M85 255L195 242L305 252L415 238L525 250L635 235" fill="none" stroke="var(--fad-good)" stroke-width="4"/><g fill="var(--fad-amber)"><circle cx="195" cy="242" r="6"/><circle cx="305" cy="252" r="6"/><circle cx="415" cy="238" r="6"/><circle cx="525" cy="250" r="6"/><circle cx="635" cy="235" r="6"/></g><text x="515" y="150" fill="var(--fad-danger)">攒到崩溃再重建</text><text x="410" y="225" fill="var(--fad-good)">固定周期的小步维护</text><text x="380" y="335" text-anchor="middle" fill="var(--fad-muted)">越早、越小地介入，边际成本越低</text>'
  $map.zones='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">把秩序沉淀到外部结构里</text><rect x="60" y="70" width="260" height="230" rx="18" fill="var(--fad-surface-2)" stroke="var(--fad-danger)"/><g fill="var(--fad-amber)"><circle cx="110" cy="120" r="10"/><circle cx="245" cy="150" r="12"/><rect x="125" y="225" width="55" height="20" rx="4"/><rect x="225" y="245" width="45" height="18" rx="4"/></g><text x="190" y="325" text-anchor="middle" fill="var(--fad-danger)">无家、远距离、不可见</text><path d="M340 185H420" stroke="var(--fad-amber)" stroke-width="4" marker-end="url(#a)"/><rect x="445" y="70" width="260" height="230" rx="18" fill="var(--fad-surface)" stroke="var(--fad-good)"/><g fill="none" stroke="var(--fad-good)"><rect x="470" y="100" width="95" height="70" rx="8"/><rect x="585" y="100" width="95" height="70" rx="8"/><rect x="470" y="190" width="210" height="75" rx="8"/></g><text x="517" y="90" text-anchor="middle" fill="var(--fad-muted)">分区 / 标签</text><text x="632" y="90" text-anchor="middle" fill="var(--fad-muted)">一物一家</text><text x="575" y="235" text-anchor="middle" fill="var(--fad-ink)" font-weight="700">对的行为成为最短路径</text><text x="575" y="325" text-anchor="middle" fill="var(--fad-good)">结构替大脑保存秩序</text>'
  $map.personal='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">个人最小秩序系统</text><circle cx="380" cy="180" r="72" fill="rgba(217,155,66,.15)" stroke="var(--fad-amber)" stroke-width="3"/><text x="380" y="174" text-anchor="middle" fill="var(--fad-ink)" font-weight="700">低耗维护</text><text x="380" y="198" text-anchor="middle" fill="var(--fad-ink)" font-weight="700">一个领域</text><g fill="var(--fad-surface)" stroke="var(--fad-good)"><rect x="80" y="95" width="155" height="70" rx="14"/><rect x="525" y="95" width="155" height="70" rx="14"/><rect x="302" y="265" width="155" height="70" rx="14"/></g><text x="157" y="136" text-anchor="middle" fill="var(--fad-ink)">家居与物品</text><text x="602" y="136" text-anchor="middle" fill="var(--fad-ink)">数字生活</text><text x="380" y="306" text-anchor="middle" fill="var(--fad-ink)">财务与衣橱</text><g stroke="var(--fad-amber)" stroke-width="3"><line x1="235" y1="130" x2="315" y2="165"/><line x1="525" y1="130" x2="445" y2="165"/><line x1="380" y1="252" x2="380" y2="265"/></g>'
  $map.workflow='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">工作信息流：每类信息只有一个确定去处</text><g fill="var(--fad-surface)" stroke="var(--fad-good)"><rect x="55" y="135" width="130" height="80" rx="14"/><rect x="230" y="75" width="130" height="80" rx="14"/><rect x="230" y="220" width="130" height="80" rx="14"/><rect x="420" y="75" width="130" height="80" rx="14"/><rect x="420" y="220" width="130" height="80" rx="14"/><rect x="595" y="135" width="120" height="80" rx="14"/></g><g text-anchor="middle" fill="var(--fad-ink)"><text x="120" y="180">输入消息</text><text x="295" y="120">任务系统</text><text x="295" y="265">日历</text><text x="485" y="120">知识文档</text><text x="485" y="265">决策记录</text><text x="655" y="180">清晰产出</text></g><g stroke="var(--fad-amber)" stroke-width="3" marker-end="url(#a)"><line x1="185" y1="165" x2="230" y2="125"/><line x1="185" y1="195" x2="230" y2="250"/><line x1="360" y1="115" x2="420" y2="115"/><line x1="360" y1="260" x2="420" y2="260"/><line x1="550" y1="115" x2="595" y2="160"/><line x1="550" y1="260" x2="595" y2="200"/></g>'
  $map.steps='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">30 天，不靠爆发，分四周搭起系统</text><path d="M80 285C190 285 190 225 300 225S410 160 520 160S610 90 690 90" fill="none" stroke="var(--fad-amber)" stroke-width="6"/><g fill="var(--fad-surface)" stroke="var(--fad-amber)" stroke-width="3"><circle cx="120" cy="285" r="34"/><circle cx="315" cy="225" r="34"/><circle cx="520" cy="160" r="34"/><circle cx="680" cy="90" r="34"/></g><g text-anchor="middle" fill="var(--fad-ink)" font-weight="700"><text x="120" y="282">第1周</text><text x="120" y="300" font-size="10">诊断减量</text><text x="315" y="222">第2周</text><text x="315" y="240" font-size="10">建立系统</text><text x="520" y="157">第3周</text><text x="520" y="175" font-size="10">植入节奏</text><text x="680" y="87">第4周</text><text x="680" y="105" font-size="10">巩固迭代</text></g><text x="380" y="335" text-anchor="middle" fill="var(--fad-muted)">每天 ≤ 15 分钟；允许漏做，但不连断两次</text>'
  $map.review='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">日、周、月三层反馈循环</text><g fill="none" stroke-width="12"><circle cx="380" cy="185" r="130" stroke="rgba(217,155,66,.2)"/><circle cx="380" cy="185" r="92" stroke="rgba(54,129,107,.22)"/><circle cx="380" cy="185" r="52" stroke="rgba(24,54,87,.28)"/></g><g text-anchor="middle" font-weight="700"><text x="380" y="190" fill="var(--fad-ink)">每日 1—2 分钟</text><text x="380" y="105" fill="var(--fad-good)">每周 15 分钟：修一个系统</text><text x="380" y="330" fill="var(--fad-amber)">每月 30 分钟：减量与扩展</text></g><path d="M500 80C650 130 650 250 500 300" fill="none" stroke="var(--fad-amber)" stroke-width="3" marker-end="url(#a)"/><text x="630" y="190" text-anchor="middle" fill="var(--fad-muted)">读信号 → 改系统</text>'
  $map.toolbox='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">九类模板：按问题取用，不要一次全上</text><rect x="95" y="75" width="570" height="225" rx="24" fill="var(--fad-surface-2)" stroke="var(--fad-amber)" stroke-width="3"/><path d="M265 75V45H495V75" fill="none" stroke="var(--fad-amber)" stroke-width="8"/><g fill="var(--fad-surface)" stroke="var(--fad-good)"><rect x="125" y="110" width="150" height="55" rx="10"/><rect x="305" y="110" width="150" height="55" rx="10"/><rect x="485" y="110" width="150" height="55" rx="10"/><rect x="125" y="195" width="150" height="55" rx="10"/><rect x="305" y="195" width="150" height="55" rx="10"/><rect x="485" y="195" width="150" height="55" rx="10"/></g><g text-anchor="middle" fill="var(--fad-ink)" font-size="12"><text x="200" y="143">熵增体检</text><text x="380" y="143">源头减量</text><text x="560" y="143">一物一家</text><text x="200" y="228">每日 / 每周维护</text><text x="380" y="228">习惯养成</text><text x="560" y="228">团队协作</text></g><text x="380" y="335" text-anchor="middle" fill="var(--fad-muted)">模板是外部秩序：把需要记忆的步骤交给结构</text>'
  $map.decision='<text x="380" y="28" text-anchor="middle" fill="var(--fad-ink)" font-size="17" font-weight="700">工具选择决策树：先问题，后工具</text><rect x="280" y="55" width="200" height="55" rx="12" fill="var(--fad-surface)" stroke="var(--fad-amber)"/><text x="380" y="88" text-anchor="middle" fill="var(--fad-ink)" font-weight="700">它降低了真实摩擦吗？</text><path d="M330 110L190 175M430 110L570 175" stroke="var(--fad-amber)" stroke-width="3"/><rect x="80" y="175" width="220" height="70" rx="14" fill="rgba(181,92,76,.12)" stroke="var(--fad-danger)"/><rect x="460" y="175" width="220" height="70" rx="14" fill="rgba(54,129,107,.12)" stroke="var(--fad-good)"/><text x="190" y="205" text-anchor="middle" fill="var(--fad-danger)" font-weight="700">没有：不要增加新系统</text><text x="190" y="226" text-anchor="middle" fill="var(--fad-muted)" font-size="11">工具本身也会产生维护成本</text><text x="570" y="205" text-anchor="middle" fill="var(--fad-good)" font-weight="700">有：再看是否足够简单</text><text x="570" y="226" text-anchor="middle" fill="var(--fad-muted)" font-size="11">默认、可迁移、易导出</text><path d="M570 245V305" stroke="var(--fad-good)" stroke-width="3" marker-end="url(#a)"/><text x="570" y="330" text-anchor="middle" fill="var(--fad-good)">选择最小可用工具栈</text>'
  return $head+$map[$type]+$tail
}

function ChapterNav([string]$current,[bool]$mobile=$false){
  $p=$byId[$current];$ids=$groups[$p.Group].Ids;$s='<ul class="fad-chapter-nav">'
  foreach($id in $ids){$x=$byId[$id];$active=if($id -eq $current){' active'}else{''};$s+='<li><a class="'+$active.Trim()+'" href="'+$x.File+'"><span class="nav-state">'+$x.Index.ToString('00')+'</span><span>'+(E $x.Label)+'</span></a></li>'}
  return $s+'</ul>'
}

foreach($page in $pages){
  $sourcePath=Join-Path $SourceRoot $page.Source;$md=[IO.File]::ReadAllText($sourcePath)
  $title=[regex]::Match($md,'(?m)^#\s+(.+)$').Groups[1].Value.Trim();$problem=[regex]::Match($md,'(?m)^>\s*本篇解决：(.+)$').Groups[1].Value.Trim()
  $md=[regex]::Replace($md,'(?m)^#\s+.+\r?\n?','',1);$md=[regex]::Replace($md,'(?m)^>\s*本篇解决：.+\r?\n?','',1)
  $toc=@();$body=Markdown $md $page.Source ([ref]$toc) ($page.Id -eq 'templates')
  if($page.Group -eq 'cases'){$body=$body -replace '<li><label><input class="fad-check"','<li><label><input class="fad-check"'}
  $tocHtml=($toc|Where-Object{$_.Level -eq 2}|ForEach-Object{'<a data-toc href="#'+$_.Id+'">'+(E $_.Title)+'</a>'}) -join ''
  $prev=if($page.Index -gt 1){$pages[$page.Index-2]}else{$null};$next=if($page.Index -lt $pages.Count){$pages[$page.Index]}else{$null}
  if($prev){$prevHtml='<a href="'+$prev.File+'"><small>← 上一篇</small><strong>'+(E $prev.Label)+'</strong></a>'}else{$prevHtml='<a href="index.html"><small>← 返回</small><strong>专题首页</strong></a>'}
  if($next){$nextHtml='<a class="next" href="'+$next.File+'"><small>下一篇 →</small><strong>'+(E $next.Label)+'</strong></a>'}else{$nextHtml='<a class="next" href="index.html"><small>完成 →</small><strong>返回知识地图</strong></a>'}
  $pagination='<nav class="fad-pagination">'+$prevHtml+$nextHtml+'</nav>'
  $templateActions=if($page.Id -eq 'templates'){'<div class="fad-template-actions"><button class="fad-inline-btn" data-reset-checks>重置全部勾选</button></div>'}else{''}
  $html=@"
<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><meta name="description" content="$(E $problem)"><title>$(E $title) · 对抗无序</title><script>(function(){var t=localStorage.getItem('hk-theme')||'light';document.documentElement.setAttribute('data-theme',t)})();</script><link rel="stylesheet" href="assets/style.css"><link rel="stylesheet" href="../assets/storygarden.css"></head>
<body class="fad" data-sg-page data-sg-section="disorder" data-sg-title="$(E $title)" data-sg-root=".." data-sg-parent="index.html" data-sg-parent-label="返回对抗无序" data-fad-id="$($page.Id)">
<div hidden>$allNav</div><div class="fad-article-shell"><aside class="fad-rail"><a class="fad-rail-home" href="index.html">← 对抗无序</a><p class="fad-rail-title">$(E $page.GroupName)</p>$(ChapterNav $page.Id)</aside><main class="fad-article"><header class="fad-article-header"><span class="fad-kicker">Chapter $($page.Index.ToString('00')) · $(E $page.GroupName)</span><h1>$(E $title)</h1><p class="question">$(E $problem)</p><div class="fad-meta"><span>约 $($page.Minutes) 分钟</span><span>第 $($page.Index) / 23 篇</span><span>离线可读</span></div></header>
$(Diagram $page.Visual $title)
<details class="fad-mobile-tools"><summary>本章目录</summary>$(ChapterNav $page.Id)</details>
<article class="fad-body">$templateActions$body<div class="fad-micro"><b>现在就试一下：</b>$(E $page.Micro)</div></article>$pagination</main>
<aside class="fad-aside"><div class="fad-card fad-aside-card"><h3>本篇解决</h3><p>$(E $problem)</p></div><div class="fad-card fad-aside-card"><h3>本页目录</h3><nav class="fad-page-toc">$tocHtml</nav></div></aside></div>
<script src="../assets/search-index.js"></script><script src="../assets/storygarden.js"></script><script src="assets/app.js"></script></body></html>
"@
  [IO.File]::WriteAllText((Join-Path $OutRoot $page.File),$html,$utf8)
}

function HeroSvg(){return @'
<svg viewBox="0 0 720 520" role="img" aria-label="混乱粒子经过能量与结构后形成秩序"><defs><marker id="ha" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 8 4 0 8Z" fill="#efb65d"/></marker><linearGradient id="beam" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#86a8c7"/><stop offset=".55" stop-color="#efb65d"/><stop offset="1" stop-color="#69b89d"/></linearGradient></defs><text x="105" y="52" fill="#aebed0" font-size="13">无干预 · 状态扩散</text><text x="558" y="52" fill="#f2c879" font-size="13">持续供能 · 结构稳定</text><g class="particle" fill="#91aac1"><circle cx="90" cy="120" r="8"/><circle cx="190" cy="92" r="5"/><circle cx="130" cy="210" r="11"/><circle cx="230" cy="175" r="7"/><circle cx="75" cy="315" r="6"/><circle cx="205" cy="360" r="10"/><circle cx="155" cy="410" r="6"/></g><g class="particle" fill="#efb65d"><rect x="105" y="155" width="35" height="13" rx="3" transform="rotate(25 105 155)"/><rect x="190" y="265" width="45" height="15" rx="3" transform="rotate(-18 190 265)"/><rect x="82" y="375" width="38" height="14" rx="3" transform="rotate(13 82 375)"/></g><path d="M270 255H435" stroke="url(#beam)" stroke-width="7" marker-end="url(#ha)"/><circle cx="350" cy="255" r="42" fill="none" stroke="#efb65d" stroke-width="2" stroke-dasharray="6 6"/><text x="350" y="251" text-anchor="middle" fill="#f2c879" font-size="12" font-weight="700">最小</text><text x="350" y="270" text-anchor="middle" fill="#f2c879" font-size="12" font-weight="700">能耗</text><rect x="455" y="82" width="210" height="360" rx="24" fill="rgba(255,255,255,.035)" stroke="#66829f"/><g stroke="#66829f"><line x1="525" y1="82" x2="525" y2="442"/><line x1="595" y1="82" x2="595" y2="442"/><line x1="455" y1="172" x2="665" y2="172"/><line x1="455" y1="262" x2="665" y2="262"/><line x1="455" y1="352" x2="665" y2="352"/></g><g fill="#69b89d"><circle cx="490" cy="127" r="10"/><circle cx="560" cy="127" r="10"/><circle cx="630" cy="127" r="10"/><circle cx="490" cy="217" r="10"/><circle cx="560" cy="217" r="10"/><circle cx="630" cy="217" r="10"/><circle cx="490" cy="307" r="10"/><circle cx="560" cy="307" r="10"/><circle cx="630" cy="307" r="10"/><circle cx="490" cy="397" r="10"/><circle cx="560" cy="397" r="10"/><circle cx="630" cy="397" r="10"/></g><text x="360" y="492" text-anchor="middle" fill="#aebed0" font-size="13">秩序不是静止，而是一个持续获得低成本供能的开放系统</text></svg>
'@}
$groupMap='';$groupIndex=0;foreach($key in $groups.Keys){$groupIndex++;$g=$groups[$key];$first=$byId[$g.Ids[0]];$groupMap+='<a class="fad-card map-stop" href="'+$first.File+'"><span class="stop-num">'+$groupIndex.ToString('00')+'</span><span><h3>'+(E $g.Name)+'</h3><p>'+(E $g.Goal)+'</p></span><span class="stop-count">'+$g.Ids.Count+' 篇</span></a>'}
$homeHtml=@"
<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><meta name="description" content="把熵增定律翻译成生活与工作中对抗无序的实操方法"><title>对抗无序 · 用最小的能量维持秩序</title><script>(function(){var t=localStorage.getItem('hk-theme')||'light';document.documentElement.setAttribute('data-theme',t)})();</script><link rel="stylesheet" href="assets/style.css"><link rel="stylesheet" href="../assets/storygarden.css"></head><body class="fad" data-sg-page data-sg-section="disorder" data-sg-title="对抗无序" data-sg-root=".." data-sg-parent="../index.html" data-sg-parent-label="返回 StoryGarden">
<div hidden>$allNav</div><header class="fad-home-hero" id="top"><div class="fad-container fad-hero-grid"><div><span class="fad-kicker">Fighting Against Disorder</span><h1>对抗无序</h1><p class="lead">你不是不自律，只是系统正在熵增。</p><p class="thesis">用最小的能量，在一个必然变乱的世界里维持秩序。这里不承诺一次整理、永不复乱；它教你把秩序交给源头、默认值、结构和小步维护。</p><div class="fad-hero-actions"><a class="fad-btn primary" href="minimum-energy.html">20 分钟快速上手</a><a class="fad-btn ghost" href="entropy-basics.html">从原理彻底理解</a><a class="fad-btn ghost" href="team-entropy.html">我是团队管理者</a></div></div><div class="fad-hero-visual">$(HeroSvg)</div></div></header>
<section class="fad-section"><div class="fad-container"><div class="fad-section-head"><span class="fad-kicker">Symptoms</span><h2>你可能正在经历这些</h2><p>混乱跨越不同场景，却总有相似的症状：东西只进不出、搜索变慢、例外变多、维护被不断推迟。</p></div><div class="pain-grid"><a class="fad-card pain-card" href="messy-room.html"><span class="pain-icon">室</span><h3>房间总会复乱</h3><p>大扫除后只维持几天，暂放区再次长出来。</p></a><a class="fad-card pain-card" href="digital-clutter.html"><span class="pain-icon">档</span><h3>文件越来越多</h3><p>真正需要时，却找不到那份“最终版”。</p></a><a class="fad-card pain-card" href="overloaded-calendar.html"><span class="pain-icon">时</span><h3>日程被塞满</h3><p>一直很忙，重要的事情仍没有推进。</p></a><a class="fad-card pain-card" href="team-entropy.html"><span class="pain-icon">协</span><h3>团队越来越慢</h3><p>会议、文档、补丁和例外一起膨胀。</p></a><a class="fad-card pain-card" href="habit-decay.html"><span class="pain-icon">习</span><h3>习惯悄悄消失</h3><p>不是突然放弃，而是在波动中慢慢衰减。</p></a></div></div></section>
<section class="fad-section alt"><div class="fad-container"><div class="fad-section-head"><span class="fad-kicker">The Model</span><h2>一张图看懂全站逻辑</h2><p>熵增不是某个场景的偶发问题，而是一条可以被识别、干预和持续管理的通用链路。</p></div><div class="fad-card logic-panel"><svg viewBox="0 0 1100 420" role="img" aria-label="熵增循环和三大干预杠杆"><defs><marker id="m" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 8 4 0 8Z" fill="var(--fad-amber)"/></marker></defs><g fill="var(--fad-surface-2)" stroke="var(--fad-border)"><rect x="35" y="145" width="205" height="100" rx="18"/><rect x="295" y="145" width="205" height="100" rx="18"/><rect x="555" y="145" width="205" height="100" rx="18"/><rect x="815" y="145" width="250" height="100" rx="18"/></g><g text-anchor="middle" fill="var(--fad-ink)" font-weight="700"><text x="137" y="190">输入不断增加</text><text x="397" y="190">状态数量膨胀</text><text x="657" y="190">搜索与维护成本上升</text><text x="940" y="190">系统滑向混乱</text></g><g text-anchor="middle" fill="var(--fad-muted)" font-size="12"><text x="137" y="216">物品 · 消息 · 承诺</text><text x="397" y="216">位置 · 版本 · 例外</text><text x="657" y="216">找、选、等、返工</text><text x="940" y="216">回潮 · 堵塞 · 崩溃</text></g><g stroke="var(--fad-amber)" stroke-width="4" marker-end="url(#m)"><line x1="240" y1="195" x2="295" y2="195"/><line x1="500" y1="195" x2="555" y2="195"/><line x1="760" y1="195" x2="815" y2="195"/></g><g fill="rgba(217,155,66,.12)" stroke="var(--fad-amber)"><rect x="85" y="300" width="210" height="70" rx="16"/><rect x="445" y="300" width="210" height="70" rx="16"/><rect x="805" y="300" width="210" height="70" rx="16"/></g><g text-anchor="middle" fill="var(--fad-ink)" font-weight="700"><text x="190" y="342">源头减量</text><text x="550" y="342">系统与默认</text><text x="910" y="342">小步高频维护</text></g><g stroke="var(--fad-good)" stroke-width="3" marker-end="url(#m)"><path d="M190 300V260"/><path d="M550 300C550 270 465 270 430 245"/><path d="M910 300V250"/></g></svg></div></div></section>
<section class="fad-section"><div class="fad-container"><div class="fad-section-head"><span class="fad-kicker">Learning Routes</span><h2>按你的目的，选一条最省力的路线</h2></div><div class="route-grid"><div class="fad-card route"><span class="fad-kicker">Route A</span><h3>快速上手</h3><p>不先啃原理，直接拿到全站最重要的心法与行动入口。</p><div class="route-meta"><span class="chip">约 20 分钟</span><span class="chip">4 篇</span></div><ol><li>最小能耗原则</li><li>从源头减少熵</li><li>30 天行动计划</li><li>清单与模板</li></ol><a class="fad-btn primary" href="minimum-energy.html">开始快速路线</a></div><div class="fad-card route"><span class="fad-kicker">Route B</span><h3>彻底理解</h3><p>从物理直觉到生活映射，再让方法从原理中自然长出来。</p><div class="route-meta"><span class="chip">约 1.5 小时</span><span class="chip">23 篇</span></div><ol><li>理解原理</li><li>建立认知</li><li>挑选案例</li><li>掌握方法并落地</li></ol><a class="fad-btn" href="entropy-basics.html">从第一篇开始</a></div><div class="fad-card route"><span class="fad-kicker">Route C</span><h3>团队 / 项目管理</h3><p>看懂协作复杂度为什么增长，并把秩序沉淀进工作系统。</p><div class="route-meta"><span class="chip">约 25 分钟</span><span class="chip">3 篇</span></div><ol><li>团队协作的熵增</li><li>建立系统而非意志</li><li>工作场景落地</li></ol><a class="fad-btn" href="team-entropy.html">进入团队路线</a></div></div></div></section>
<section class="fad-section alt" id="map"><div class="fad-container"><div class="fad-section-head"><span class="fad-kicker">Knowledge Map</span><h2>从混乱走向秩序的六站地图</h2><p>按原理、认知、案例、方法、落地与工具，循序进入完整知识体系。</p></div><div class="map-list">$groupMap</div></div></section>
<section class="fad-section"><div class="fad-container"><div class="fad-section-head"><span class="fad-kicker">Minimum Energy</span><h2>全站核心：三大杠杆</h2></div><div class="lever-grid"><div class="fad-card lever feature"><span class="lever-num">01</span><h3>源头减量</h3><p>不是更努力地整理，而是让“需要整理”的事情更少发生。减少量、种类与复杂度，并守住入口。</p><div class="energy-compare"><b>最高性价比：</b>少一份输入，就永久少一份分类、寻找和维护成本。</div></div><div class="fad-card lever"><span class="lever-num">02</span><h3>系统与默认</h3><p>用默认值、自动化、摩擦和清单，把秩序从“靠人记得”转移到“环境自动兜住”。</p></div><div class="fad-card lever"><span class="lever-num">03</span><h3>小步高频</h3><p>在混乱还小的时候介入，每天两分钟往往比每月一次大扫除更便宜。</p></div><div class="fad-card lever"><span class="fad-kicker">Energy</span><h3>意志力是最贵的能量</h3><p>目标决定方向，系统决定结果。真正稳定的秩序，应该让正确动作成为阻力最小的路径。</p></div><div class="fad-card lever"><span class="fad-kicker">Rule</span><h3>三个月后还愿意做吗？</h3><p>如果一种方法太麻烦、太耗神，它迟早会被废弃。可持续的低能耗，胜过偶尔的高强度。</p></div></div></div></section>
<section class="fad-section alt"><div class="fad-container"><div class="fad-section-head"><span class="fad-kicker">By Scenario</span><h2>从你正在遭遇的问题进入</h2></div><div class="scene-links"><a href="messy-room.html">我的房间很乱</a><a href="digital-clutter.html">我的数字资料失控</a><a href="overloaded-calendar.html">我的时间被塞满</a><a href="team-entropy.html">我的团队越来越低效</a><a href="habit-decay.html">我的习惯总是中断</a></div></div></section>
<section class="fad-section"><div class="fad-container"><div class="fad-card action-panel"><div><span class="fad-kicker">30-Day Action</span><h2>每天不超过 15 分钟</h2><p>一次只改一个领域；先建系统，再谈维护。允许漏做，但不连续漏掉两次。</p><a class="fad-btn primary" href="thirty-day-plan.html">开始 30 天计划</a></div><div class="week-steps"><div class="week"><b>第 1 周</b>诊断减量</div><div class="week"><b>第 2 周</b>建立系统</div><div class="week"><b>第 3 周</b>植入节奏</div><div class="week"><b>第 4 周</b>巩固迭代</div></div></div></div></section>
<section class="fad-section alt"><div class="fad-container"><div class="fad-section-head"><span class="fad-kicker">Mantras</span><h2>读完全站，希望你记住这四句</h2></div><div class="mantra-grid"><div class="fad-card mantra">无序是默认，有序需要主动供能。</div><div class="fad-card mantra">与其事后大扫除，不如从源头减少熵的产生。</div><div class="fad-card mantra">意志力最贵，默认值、自动化与结构更便宜。</div><div class="fad-card mantra">小步高频维护，比崩溃后重建更省力。</div></div></div></section><footer class="fad-home-footer"><strong>秩序不是终点，而是一种低能耗的持续过程。</strong><span>用系统替代自责，用微小而稳定的供能对抗无序。</span></footer>
<script src="../assets/search-index.js"></script><script src="../assets/storygarden.js"></script><script src="assets/app.js"></script></body></html>
"@
[IO.File]::WriteAllText((Join-Path $OutRoot 'index.html'),$homeHtml,$utf8)
Write-Output ('Generated home + {0} article pages in {1}' -f $pages.Count,$OutRoot)
